module Main where

import Control.Monad (when)
import Data.Maybe (fromMaybe)
import Data.Text qualified as Text
import LambdaSound
import Options.Applicative
import Paths_voice_box
import System.Exit (exitFailure, exitSuccess)
import System.FilePath (dropExtension, takeExtension, (<.>))
import Voice.IPA
import Voice.Synth
import Voice.Util (writeFileUtf8)
import VoiceBox.Analyze (analyzeAudio, readWaveFile, writeWaveFile)
import VoiceBox.Transform qualified as Transform
import VoiceBox.Types qualified as VB
import Data.Foldable (forM_)

-- | Command-line options
data Options = Options
  { optInputFile :: FilePath,
    optOutputFile :: Maybe FilePath,
    optSampleRate :: Int,
    optDebug :: Bool,
    -- | Force analysis mode (extract features from WAV)
    optAnalyze :: Bool,
    -- | Force synthesis mode (generate audio from text)
    optSynthesize :: Bool,
    -- | Apply PreDoll-0 transformation to WAV input
    optTransform :: Bool
  }
  deriving (Show)

-- | Parse command-line options
optionsParser :: Parser Options
optionsParser =
  Options
    <$> argument
      str
      ( metavar "INPUT"
          <> help "Input file (text for synthesis, or .wav for analysis)"
      )
    <*> optional
      ( strOption
          ( long "output"
              <> short 'o'
              <> metavar "FILE"
              <> help "Output WAV file (default: INPUT.wav)"
          )
      )
    <*> option
      auto
      ( long "sample-rate"
          <> short 'r'
          <> metavar "HZ"
          <> value 44100
          <> showDefault
          <> help "Sample rate for output audio"
      )
    <*> switch
      ( long "debug"
          <> short 'd'
          <> help "Write debug output (with --transform: intermediate stage WAV files)"
      )
    <*> switch
      ( long "analyze"
          <> short 'a'
          <> help "Analyze WAV file (extract features)"
      )
    <*> switch
      ( long "synthesize"
          <> short 's'
          <> help "Synthesize audio from text"
      )
    <*> switch
      ( long "transform"
          <> short 't'
          <> help "Apply PreDoll-0 voice transformation to WAV input"
      )

-- | Options with help/description
opts :: ParserInfo Options
opts =
  info
    (optionsParser <**> helper <**> versionOption)
    ( fullDesc
        <> progDesc "Synthesize audio from text or analyze WAV files"
        <> header "voice-box - a speech synthesizer and analyzer for conlangs"
    )
  where
    -- Version info comes from Paths_voice_box (auto-generated by Cabal)
    versionOption =
      infoOption
        ("voice-box version " <> show version)
        ( long "version"
            <> short 'v'
            <> help "Show version information"
        )

main :: IO ()
main = execParser opts >>= processFile

-- | Main dispatcher: routes to analysis, synthesis, or transformation based on flags/extension
processFile :: Options -> IO ()
processFile optsValues = do
  let path = optInputFile optsValues
  let ext = takeExtension path

  -- Check for transform mode first
  when (optTransform optsValues) $ do
    transformWavFile optsValues path
    exitSuccess

  -- Decision logic for analysis vs synthesis:
  -- 1. Error if both --analyze and --synthesize are specified
  -- 2. Use explicit flag if only one is present
  -- 3. Auto-detect from file extension if neither flag is present
  --    (.wav → analyze, anything else → synthesize)
  case (optAnalyze optsValues, optSynthesize optsValues) of
    (True, True) -> do
      putStrLn "Error: Cannot specify both --analyze and --synthesize flags"
      exitFailure
    (True, False) -> analyzeWavFile optsValues path
    (False, True) -> synthesizeFromText optsValues path
    (False, False) ->
      -- Auto-detect from extension
      if ext == ".wav"
        then analyzeWavFile optsValues path
        else synthesizeFromText optsValues path

-- | Analyze a WAV file and print extracted features (pitch, envelope, formants, segments)
analyzeWavFile :: Options -> FilePath -> IO ()
analyzeWavFile optsValues path = do
  putStrLn $ "Analyzing WAV file: " ++ path
  features <- analyzeAudio path

  -- Print summary counts
  putStrLn "\n=== Analysis Results ==="
  putStrLn $ "Pitch samples: " ++ show (length $ VB.afPitch features)
  putStrLn $ "Envelope samples: " ++ show (length $ VB.afEnvelope features)
  putStrLn $ "Formant frames: " ++ show (length $ VB.afFormants features)
  putStrLn $ "Segments: " ++ show (length $ VB.afSegments features)

  -- In debug mode, print detailed feature data
  when (optDebug optsValues) $ do
    putStrLn "\nFirst 10 pitch detections:"
    mapM_
      (\p -> putStrLn $ "  Time: " ++ show (VB.pitchTime p) ++ "s, Freq: " ++ show (VB.pitchFreq p) ++ " Hz")
      (take 10 $ VB.afPitch features)

    putStrLn "\nFirst 10 envelope samples:"
    mapM_
      (\e -> putStrLn $ "  Time: " ++ show (VB.ampTime e) ++ "s, Amplitude: " ++ show (VB.ampMagnitude e))
      (take 10 $ VB.afEnvelope features)

    putStrLn "\nDetected segments:"
    mapM_
      (\s -> putStrLn $ "  " ++ VB.segLabel s ++ ": " ++ show (VB.segStart s) ++ "s - " ++ show (VB.segEnd s) ++ "s")
      (VB.afSegments features)

  exitSuccess

-- | Transform a WAV file with PreDoll-0 voice effects
transformWavFile :: Options -> FilePath -> IO ()
transformWavFile optsValues path = do
  putStrLn $ "Applying PreDoll-0 transformation to: " ++ path

  -- Determine output path
  let outputFile = fromMaybe (dropExtension path ++ "_predoll0.wav") (optOutputFile optsValues)
  -- In debug mode, write intermediate stage files for isolation
  if optDebug optsValues
    then do
      audioResult <- readWaveFile path
      case audioResult of
        Left err -> do
          putStrLn $ "Error reading WAV file for debug transform: " ++ err
          exitFailure
        Right (samples, sampleRate) -> do
          let stages = Transform.transformStages sampleRate Transform.preDoll0Params samples
              base = dropExtension outputFile
          -- Write each stage to its own WAV file
          mapM_ (\(name, vec) -> writeWaveFile (base ++ "_" ++ name ++ ".wav") sampleRate vec) stages
          putStrLn $ "Wrote " ++ show (length stages) ++ " debug stage files with base: " ++ base
          -- Also write the final stage to the requested output path
          lookup "99_final" stages `forM_` writeWaveFile outputFile sampleRate
          putStrLn "Debug transformation complete."
          exitSuccess
    else do
      -- Use the helper from VoiceBox.Transform (direct WAV -> WAV)
      maybeErr <- Transform.transformWavFile path outputFile

      case maybeErr of
        Just err -> do
          putStrLn $ "Error transforming WAV file: " ++ err
          exitFailure
        Nothing -> do
          putStrLn $ "Saved transformed audio to: " ++ outputFile
          putStrLn "Transformation complete!"
          exitSuccess
-- | Synthesize audio from a text file containing IPA/romanized input

synthesizeFromText :: Options -> FilePath -> IO ()
synthesizeFromText optsValues path = do
  -- parseFile returns [[Foot]] - a list of utterances, each containing feet
  result <- Voice.IPA.parseFile path
  putStrLn $ "Parsed " ++ show (length result) ++ " utterances."

  -- Print hierarchical structure stats: utterances → feet → phonemes
  let feetCount = length <$> result
  putStrLn $ "Utterance lengths (in feet): " ++ show feetCount

  let feetLengths = (length <$>) <$> result
  putStrLn $ "Feet length (in phonemes): " ++ show feetLengths

  let utterancePhonemes = fmap (fmap length) result
  putStrLn $ "Utterance lengths (in phonemes): " ++ show utterancePhonemes

  let totalPhonemes = sum (fmap sum utterancePhonemes)
  putStrLn $ "Total phonemes: " ++ show totalPhonemes

  -- Debug: write the parsed AST structure to a .debug file
  when (optDebug optsValues) $
    writeFileUtf8 (path <.> "debug") (Text.show result)

  -- Synthesize sound using LambdaSound backend
  putStrLn "Beginning synthesis..."
  let sound = paragraphsToSound result

  -- Determine output path: use --output flag or default to INPUT.wav
  let soundFile = fromMaybe (dropExtension path <.> "wav") (optOutputFile optsValues)
  let sampleRate = Hz (fromIntegral $ optSampleRate optsValues)
  putStrLn $ "Saving " <> soundFile <> " ..."
  saveWav soundFile sampleRate sound

  -- Commented out: could add real-time playback here if desired
  -- putStrLn "Playing sound."
  -- play (optSampleRate opts) 1.0 sound

  exitSuccess
